### ISSUE TITLE
PSR-2 coding style

### ISSUE THREAD

**Issue by peter279k** [phootwork/file#6]
@gossi, do you consider using the [PSR-2 coding style](https://www.php-fig.org/psr/psr-2/) for this project?

If possible, I can help this issue. And we have following solutions to help us to check coding style.

- [StyleCI](https://styleci.io)
- [PHP_CodSniffer](https://github.com/squizlabs/PHP_CodeSniffer/releases/)
- [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by gossi** [comment]
Absolutely ... not! But there is https://github.com/gossi/php-cs-fixer-config for the cs-fixer-config (perhaps not yet added to this project).

**Comment by peter279k** [comment]
Hi @gossi, I see that.

Some packages has been included this `php-csfixer-config` and I think this should be added, too.
